### ISSUE TITLE
How to use this IOC with PowerPMAC

### ISSUE THREAD

**Issue by gabrielfedel** [dls-controls/pmac#69]
Hi, How I can use this IOC with PowerPMAC?

I'm trying to use iocbuilder, but there are some dependencies I can't solve (dls_ade)

**Comment by gilesknap** [comment]
Hi Fedel,


If you are using the pmac driver from https://github.com/dls-controls/pmac then this can indeed drive the power pmac. Internally at Diamond we use iocbuilder to generate the source code for our IOCs and the pmac module has some sample IOCs which use this.


I would recommend that you do not try to get iocbuilder working and therefore ignore entries in the /etc folder.


There is a standalone ioc in iocs/example which is intended to build without any Diamond specific dependencies and this is what I would recommend you use.


If you are having the dependency issue with iocs/example then let me know and I will fix the problem.


Thanks,

giles.

________________________________

**Comment by gilesknap** [comment]
Hi Fedel,


If you are using the pmac driver from https://github.com/dls-controls/pmac then this can indeed drive the power pmac. Internally at Diamond we use iocbuilder to generate the source code for our IOCs and the pmac module has some sample IOCs which use this.


I would recommend that you do not try to get iocbuilder working and therefore ignore entries in the /etc folder.


There is a standalone ioc in iocs/example which is intended to build without any Diamond specific dependecies. This is the example that I would recommend you use. You can edit the startup script and database file to suit your setup.


If the example IOC is giving you the dependency issues then let me know and I will fix it.


Thanks,

giles

________________________________

**Comment by gabrielfedel** [comment]
Hi @gilesknap  Thank you for the answer!

I trying to compile iocs/example, but I having this problem:

msi    -I. -I.. -I../O.Common -I../../../db -I/usr/local/epics/synApps/support/asyn-R4-33/db -I/usr
/local/epics/synApps/support/busy-R1-7/db -I/usr/local/epics/synApps/support/motor-R6-10-1/db -I../
../../../..//db -I/usr/local/epics/base/db -S../lab_expanded.substitutions  > lab_expanded.tmp     
Could not open basic_asyn_motor.template                                                           
input: include "basic_asyn_motor.template"                                                         
  which is line 12 of  file ../../../../..//db/dls_pmac_asyn_motor.template                        



besides that, The ioc example is called "ioclab", if I can run it, it will be compatible with PowerPMAC ?

If you think better I can send an email (instead of use github issues).

**Comment by gilesknap** [comment]
OK we have two problems here.

(1) my example uses basic_asyn_motor.template which is in a DLS module so my example is not independent of DLS

(2) my example is for the delta tau pmac variant, not power pmac.


I will need to spend a little time on working out how to best provide useful examples and will get back to you next week.

Let's continue the discussion on github since it may be useful to others using this driver.

________________________________

**Comment by gabrielfedel** [comment]
Ok @gilesknap , thank you!

**Comment by gilesknap** [comment]
Closing this issue.

In summary, there is now an example in iocs/simple-power-pmac which has been tested outside of DLS.
