### ISSUE TITLE
Compile error on CentOS7

### ISSUE THREAD

**Issue by waynelewis** [dls-controls/pmac#70]
When building on CentOS7, the following compiler error occurs:

`../devPmacRam.c: In function ‘devPmacRamEvent_read’:
../devPmacRam.c:1064:13: error: incompatible types when assigning to type ‘char[40]’ from type ‘short int’
   pRec->val = (short) (0x0000ffff & pDpvt->dpramData.ramLong);
`
I will submit a pull request for review to (hopefully) address this.

**Comment by gilesknap** [comment]
See my comments in https://github.com/dls-controls/pmac/pull/71

**Comment by gilesknap** [comment]
fixed in PR #72, thanks Wayne.
