### ISSUE TITLE
Problems with PowerPMAC

### ISSUE THREAD

**Issue by gabrielfedel** [dls-controls/pmac#75]
Hi, We are having some problems with our PowerPMAC when we use an specific code inside controller (if we use factory setup this problem doesn't happen). The problem looks related with m-variables. The IOC prints messages like:

pmacController::mediumUpdate Problem reading PLC program status => M5022

Is necessary to use an specific code in DeltaTau to use the IOC? Or I can suppose any code will work?

**Comment by gilesknap** [comment]
Sorry that I did not see this ticket for ages.

These M variables are used to track which PLCs are running. Please use the mappings in etc/LabPowerPmac/PMAC Script Language/Global Includes/PowerPMAC_M_Variables.pmh
