### ISSUE TITLE
PMAC PCI

### ISSUE THREAD

**Issue by dallanporter** [dls-controls/pmac#78]
Hi,
This is a question more than an ‘issue’, so apologies if this isn’t the place to ask it. We have a PMAC PCI (the plain old PCI version—not the turbo) and we would like to retire the old XP control computer that communicates with it using the PCI bus. Does this software also support our PMAC PCI? 

Thanks!
Dallan 
MMT Observatory
Tucson, AZ

**Comment by gilesknap** [comment]
I'm afraid the answer is no. This driver relies on making a connection to the controller over a socket and also uses the Turbo PMAC script language. I would assume that both of these points are issues for your controller.

**Comment by dallanporter** [comment]
Thank you for the response. I think I understand what makes the regular PMAC different than the Turbo PMAC now. It sounds like we will need a Turbo in order to eliminate this Windows XP machine from the loop. 

Regards,
Dallan
