### ISSUE TITLE
Crash with  "floating point exception"

### ISSUE THREAD

**Issue by tyjisinap** [dls-controls/pmac#81]
Hi Giles,
I try to run the iocs/example. when run the command "pmacCreateController("Brick", "BRICK1port", 0, 8, 100, 200)" , it gives a error "floating point exception" and EPICS exist.
I use the Ubuntu 18.04LTS,   Geobrick LV . Do I use the right example for Geobrick? 
Thank you!   

Best,
Yajun

**Comment by tyjisinap** [comment]
I think it connect the Geobrick LV correctly, because when I unplug the net cable. It doesn't exist.

**Comment by gilesknap** [comment]
Hi Yajun,

I need a little more information to help diagnose this.
Please, can you send the contents of your startup script and also send the full stack trace if one was printed out?

Thanks,
giles.

**Comment by gilesknap** [comment]
I'm going to close this since there is no response, please reopen if you still need assistance.
